# Generated by Django 3.0.8 on 2020-08-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200813_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Unlikes',
            new_name='unlikes',
        ),
    ]
