# Generated by Django 3.0.8 on 2020-08-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200813_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
